const KEY='barberShopData_v2';
const today=()=>new Date().toISOString().slice(0,10);
const defaults={clients:[],services:[{id:1,name:'Corte clásico',price:20,duration:'30 min'},{id:2,name:'Fade / Degradado',price:25,duration:'45 min'},{id:3,name:'Barba',price:15,duration:'30 min'},{id:4,name:'Combo completo',price:35,duration:'60 min'}],appointments:[],shopName:'Barber Shop'};
let data=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));}
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const client=id=>data.clients.find(x=>x.id===Number(id));const service=id=>data.services.find(x=>x.id===Number(id));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function go(section){$$('.section').forEach(x=>x.classList.remove('active'));$('#'+section)?.classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===section));const titles={dashboard:'Panel general',appointments:'Agenda de citas',clients:'Clientes',services:'Servicios',reports:'Reportes',settings:'Configuración'};$('#pageTitle').textContent=titles[section]||'Barber Shop';$('#sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
function openModal(id){if(id==='appointmentModal'&&!data.clients.length){toast('Primero registra un cliente');return openModal('clientModal')}$('#'+id).classList.add('open')}function closeModal(){$$('.modal').forEach(x=>x.classList.remove('open'))}
function populate(){$('#appointmentClient').innerHTML=data.clients.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.phone)}</option>`).join('');$('#appointmentService').innerHTML=data.services.map(s=>`<option value="${s.id}">${esc(s.name)} — S/ ${Number(s.price).toFixed(2)}</option>`).join('')}
function render(){const done=data.appointments.filter(a=>a.status==='done'),revenue=done.reduce((n,a)=>n+(service(a.serviceId)?.price||0),0);$('#clientCount').textContent=data.clients.length;$('#serviceCount').textContent=data.services.length;$('#todayCount').textContent=data.appointments.filter(a=>a.date===today()&&a.status!=='done').length;$('#revenue').textContent=`S/ ${revenue.toFixed(2)}`;$('#reportRevenue').textContent=`S/ ${revenue.toFixed(2)}`;$('#reportDone').textContent=done.length;$('#shopName').value=data.shopName||'Barber Shop';renderUpcoming();renderAppointments();renderClients();renderServices();renderReport();populate()}
function renderUpcoming(){const a=data.appointments.filter(x=>x.status!=='done').sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time)).slice(0,6);$('#upcoming').innerHTML=a.length?a.map(x=>`<div class="appointment-row"><div><b>${esc(client(x.clientId)?.name||'Cliente')}</b><small>${esc(service(x.serviceId)?.name||'Servicio')} · ${x.date}</small></div><strong>${x.time}</strong><span class="status pending">Pendiente</span></div>`).join(''):'<p class="muted">No hay citas pendientes.</p>'}
function renderAppointments(){const q=($('#appointmentSearch').value||'').toLowerCase(),f=$('#appointmentFilter').value;const rows=data.appointments.filter(a=>(f==='all'||a.status===f)&&(client(a.clientId)?.name||'').toLowerCase().includes(q)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('#appointmentTable').innerHTML=rows.length?rows.map(a=>`<tr><td><b>${esc(client(a.clientId)?.name||'Cliente')}</b></td><td>${a.date}</td><td>${a.time}</td><td>${esc(service(a.serviceId)?.name||'Eliminado')}</td><td><span class="status ${a.status==='done'?'done':'pending'}">${a.status==='done'?'Completada':'Pendiente'}</span></td><td>${a.status==='pending'?`<button class="table-action" data-done="${a.id}">✓ Marcar completada</button>`:`<button class="table-action" data-delete="${a.id}">Eliminar</button>`}</td></tr>`).join(''):'<tr><td colspan="6">No hay citas.</td></tr>'}
function renderClients(){const q=($('#clientSearch').value||'').toLowerCase(),rows=data.clients.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q));$('#clientsGrid').innerHTML=rows.length?rows.map(c=>`<article class="client-card"><div class="avatar">${esc(c.name[0]?.toUpperCase()||'C')}</div><h3>${esc(c.name)}</h3><p>📞 ${esc(c.phone)}</p><p>${esc(c.note||'Sin notas')}</p><small>${data.appointments.filter(a=>a.clientId===c.id).length} cita(s)</small><button class="table-action" data-delete-client="${c.id}">Eliminar</button></article>`).join(''):'<div class="panel">No hay clientes registrados.</div>'}
function renderServices(){$('#servicesGrid').innerHTML=data.services.map(s=>`<article class="service-card"><h3>${esc(s.name)}</h3><p>${esc(s.duration)}</p><strong class="service-price">S/ ${Number(s.price).toFixed(2)}</strong><button class="table-action" data-delete-service="${s.id}">Eliminar</button></article>`).join('')}
function renderReport(){const counts={};data.appointments.filter(a=>a.status==='done').forEach(a=>{const s=service(a.serviceId);if(s)counts[s.name]=(counts[s.name]||0)+1});const max=Math.max(1,...Object.values(counts));$('#serviceReport').innerHTML=Object.entries(counts).map(([n,v])=>`<div class="bar-row"><span>${esc(n)}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('')||'<p class="muted">Completa citas para ver estadísticas.</p>'}
function download(filename,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.section)));$$('[data-section]').forEach(b=>{if(!b.classList.contains('nav'))b.addEventListener('click',()=>go(b.dataset.section))});$$('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModal));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal()}));$('#appointmentDate').value=today();
$('#appointmentForm').addEventListener('submit',e=>{e.preventDefault();data.appointments.push({id:Date.now(),clientId:Number($('#appointmentClient').value),date:$('#appointmentDate').value,time:$('#appointmentTime').value,serviceId:Number($('#appointmentService').value),status:'pending'});save();render();closeModal();e.target.reset();$('#appointmentDate').value=today();toast('Cita guardada como pendiente')});$('#clientForm').addEventListener('submit',e=>{e.preventDefault();data.clients.push({id:Date.now(),name:$('#clientName').value.trim(),phone:$('#clientPhone').value.trim(),note:$('#clientNote').value.trim()});save();render();closeModal();e.target.reset();toast('Cliente guardado')});$('#serviceForm').addEventListener('submit',e=>{e.preventDefault();data.services.push({id:Date.now(),name:$('#serviceName').value.trim(),price:Number($('#servicePrice').value),duration:$('#serviceDuration').value});save();render();closeModal();e.target.reset();toast('Servicio guardado')});
$('#appointmentTable').addEventListener('click',e=>{if(e.target.dataset.done){const a=data.appointments.find(x=>x.id===Number(e.target.dataset.done));if(a){a.status='done';save();render();toast('Cita marcada como completada')}}if(e.target.dataset.delete){data.appointments=data.appointments.filter(x=>x.id!==Number(e.target.dataset.delete));save();render();toast('Cita eliminada')}});$('#clientsGrid').addEventListener('click',e=>{if(e.target.dataset.deleteClient){data.clients=data.clients.filter(x=>x.id!==Number(e.target.dataset.deleteClient));data.appointments=data.appointments.filter(a=>a.clientId!==Number(e.target.dataset.deleteClient));save();render();toast('Cliente eliminado')}});$('#servicesGrid').addEventListener('click',e=>{if(e.target.dataset.deleteService){const id=Number(e.target.dataset.deleteService);if(data.appointments.some(a=>a.serviceId===id)){toast('No puedes eliminar un servicio usado en citas');return}data.services=data.services.filter(x=>x.id!==id);save();render();toast('Servicio eliminado')}});
$('#appointmentSearch').addEventListener('input',renderAppointments);$('#appointmentFilter').addEventListener('change',renderAppointments);$('#clientSearch').addEventListener('input',renderClients);$('#saveSettings').addEventListener('click',()=>{data.shopName=$('#shopName').value.trim()||'Barber Shop';save();toast('Configuración guardada')});$('#exportData').addEventListener('click',()=>download(`barber-shop-respaldo-${today()}.json`,JSON.stringify(data,null,2)));$('#importData').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);if(!incoming.clients||!incoming.services||!incoming.appointments)throw Error();data=incoming;save();render();toast('Respaldo restaurado correctamente')}catch{toast('El archivo no es un respaldo válido')}};reader.readAsText(file);e.target.value='' });$('#clearData').addEventListener('click',()=>{if(confirm('¿Seguro que quieres borrar todos los clientes, citas y servicios personalizados?')){data=structuredClone(defaults);save();render();toast('Datos borrados')}});render();