const KEY='barberShopData';
const today=new Date().toISOString().slice(0,10);
const defaults={clients:[{id:1,name:'Cliente de ejemplo',phone:'987 654 321',note:'Prefiere degradado bajo'}],services:[{id:1,name:'Corte clásico',price:25,duration:'45 min'},{id:2,name:'Corte + barba',price:35,duration:'60 min'},{id:3,name:'Barba',price:15,duration:'30 min'}],appointments:[{id:1,clientId:1,date:today,time:'17:00',serviceId:1,status:'pending'}],shopName:'Barber Shop'};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const client=id=>data.clients.find(x=>x.id===Number(id));
const service=id=>data.services.find(x=>x.id===Number(id));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function render(){
  $('#clientCount').textContent=data.clients.length; $('#serviceCount').textContent=data.services.length;
  const done=data.appointments.filter(a=>a.status==='done'); const revenue=done.reduce((n,a)=>n+(service(a.serviceId)?.price||0),0);
  $('#todayCount').textContent=data.appointments.filter(a=>a.date===today&&a.status!=='done').length; $('#revenue').textContent=`S/ ${revenue.toFixed(2)}`;
  $('#reportRevenue').textContent=`S/ ${revenue.toFixed(2)}`;$('#reportDone').textContent=done.length;
  renderUpcoming();renderAppointments();renderClients();renderServices();renderReport();populateSelects();
}
function renderUpcoming(){const list=$('#upcomingList');const a=data.appointments.filter(x=>x.status!=='done').sort((x,y)=>(x.date+x.time).localeCompare(y.date+y.time)).slice(0,5);list.innerHTML=a.length?a.map(x=>`<div class="appointment-row"><div class="appointment-main"><strong>${esc(client(x.clientId)?.name||'Cliente')}</strong><small>${esc(service(x.serviceId)?.name||'Servicio')} · ${x.date}</small></div><span class="time">${x.time}</span><span class="status">Pendiente</span></div>`).join(''):'<p class="muted">No hay citas pendientes.</p>'}
function renderAppointments(){const q=($('#appointmentSearch')?.value||'').toLowerCase();const f=$('#appointmentFilter')?.value||'all';const rows=data.appointments.filter(a=>(f==='all'||a.status===f)&&(client(a.clientId)?.name||'').toLowerCase().includes(q)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('#appointmentsTable').innerHTML=rows.length?rows.map(a=>`<tr><td><strong>${esc(client(a.clientId)?.name||'Cliente eliminado')}</strong></td><td>${a.date}</td><td>${a.time}</td><td>${esc(service(a.serviceId)?.name||'—')}</td><td><span class="status ${a.status==='done'?'done':''}">${a.status==='done'?'Completada':'Pendiente'}</span></td><td>${a.status==='pending'?`<button class="table-action" data-done="${a.id}">Completar</button>`:`<button class="table-action" data-delete-appointment="${a.id}">Eliminar</button>`}</td></tr>`).join(''):'<tr><td colspan="6">No se encontraron citas.</td></tr>'}
function renderClients(){const q=($('#clientSearch')?.value||'').toLowerCase();const rows=data.clients.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q));$('#clientsGrid').innerHTML=rows.map(c=>`<article class="client-card"><div class="avatar">${esc(c.name[0]?.toUpperCase()||'C')}</div><h3>${esc(c.name)}</h3><p>📞 ${esc(c.phone)}</p><p>${esc(c.note||'Sin notas')}</p><p>${data.appointments.filter(a=>a.clientId===c.id).length} cita(s) registradas</p></article>`).join('')||'<div class="panel">No hay clientes.</div>'}
function renderServices(){$('#servicesGrid').innerHTML=data.services.map(s=>`<article class="service-card"><h3>${esc(s.name)}</h3><p>Duración: ${esc(s.duration)}</p><span class="service-price">S/ ${Number(s.price).toFixed(2)}</span></article>`).join('')}
function renderReport(){const counts={};data.appointments.forEach(a=>{const s=service(a.serviceId);if(s)counts[s.name]=(counts[s.name]||0)+1});const max=Math.max(1,...Object.values(counts));$('#serviceReport').innerHTML=Object.entries(counts).map(([name,n])=>`<div class="bar-row"><span>${esc(name)}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join('')||'<p>No hay datos todavía.</p>'}
function populateSelects(){ $('#appointmentClient').innerHTML=data.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#appointmentService').innerHTML=data.services.map(s=>`<option value="${s.id}">${esc(s.name)} — S/ ${s.price}</option>`).join('')}
function openModal(id){if(id==='appointmentModal'&&!data.clients.length){toast('Primero registra un cliente');openModal('clientModal');return}$('#'+id).classList.add('open')}
function closeModals(){$$('.modal-backdrop').forEach(m=>m.classList.remove('open'))}
function go(section){$$('.section').forEach(s=>s.classList.remove('active-section'));$('#'+section).classList.add('active-section');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===section));const titles={dashboard:'Panel general',appointments:'Agenda de citas',clients:'Clientes',services:'Servicios',reports:'Reportes',settings:'Configuración'};$('#pageTitle').textContent=titles[section];$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.section)));$$('[data-section-target]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.sectionTarget)));$$('[data-open-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.openModal)));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModals));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#notificationBtn').addEventListener('click',()=>toast('No tienes nuevas notificaciones'));
$$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
$('#appointmentDate').value=today;
$('#appointmentForm').addEventListener('submit',e=>{e.preventDefault();data.appointments.push({id:Date.now(),clientId:Number($('#appointmentClient').value),date:$('#appointmentDate').value,time:$('#appointmentTime').value,serviceId:Number($('#appointmentService').value),status:'pending'});save();render();closeModals();e.target.reset();$('#appointmentDate').value=today;toast('Cita guardada correctamente')});
$('#clientForm').addEventListener('submit',e=>{e.preventDefault();data.clients.push({id:Date.now(),name:$('#clientName').value.trim(),phone:$('#clientPhone').value.trim(),note:$('#clientNote').value.trim()});save();render();closeModals();e.target.reset();toast('Cliente registrado')});
$('#serviceForm').addEventListener('submit',e=>{e.preventDefault();data.services.push({id:Date.now(),name:$('#serviceName').value.trim(),price:Number($('#servicePrice').value),duration:$('#serviceDuration').value});save();render();closeModals();e.target.reset();toast('Servicio añadido')});
$('#appointmentsTable').addEventListener('click',e=>{const done=e.target.dataset.done,del=e.target.dataset.deleteAppointment;if(done){const a=data.appointments.find(x=>x.id===Number(done));a.status='done';save();render();toast('Cita marcada como completada')}if(del){data.appointments=data.appointments.filter(x=>x.id!==Number(del));save();render();toast('Cita eliminada')}});
$('#appointmentSearch').addEventListener('input',renderAppointments);$('#appointmentFilter').addEventListener('change',renderAppointments);$('#clientSearch').addEventListener('input',renderClients);$('#saveSettings').addEventListener('click',()=>{data.shopName=$('#shopName').value.trim()||'Barber Shop';save();toast('Configuración guardada')});
render();