const KEY='barberShopData_v4';
const DEFAULT_NAME='Aquí con la familia';
const today=()=>new Date().toISOString().slice(0,10);
const defaults={appointments:[],shopName:DEFAULT_NAME};
let data=load();
function load(){try{const v4=JSON.parse(localStorage.getItem(KEY));if(v4)return {...defaults,...v4,shopName:String(v4.shopName||DEFAULT_NAME)};const v3=JSON.parse(localStorage.getItem('barberShopData_v3'));if(v3)return {...defaults,...v3,shopName:String(v3.shopName||DEFAULT_NAME)};const v2=JSON.parse(localStorage.getItem('barberShopData_v2'));if(v2?.appointments)return {...defaults,appointments:v2.appointments.map(a=>({...a,name:a.name||'Cliente',phone:a.phone||'Sin número',amount:Number(a.amount||0),status:a.status==='done'?'done':'pending'}))};return {...defaults}}catch{return {...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function go(section){$$('.section').forEach(x=>x.classList.remove('active'));$('#'+section)?.classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===section));$('#pageTitle').textContent={dashboard:'Panel general',appointments:'Agenda de citas',reports:'Reportes',settings:'Configuración'}[section]||data.shopName;$('#sidebar').classList.remove('open')}
function openModal(id){$('#'+id)?.classList.add('open')}function closeModal(){$$('.modal').forEach(x=>x.classList.remove('open'))}
function updateShopNameUI(){const name=data.shopName||DEFAULT_NAME;$$('[data-shop-name]').forEach(el=>el.textContent=name);const input=$('#shopName');if(input&&document.activeElement!==input)input.value=name;document.title=`${name} | Barbería`}
function render(){const done=data.appointments.filter(a=>a.status==='done'),pending=data.appointments.filter(a=>a.status!=='done'),revenue=done.reduce((n,a)=>n+Number(a.amount||0),0);$('#todayCount').textContent=data.appointments.filter(a=>a.date===today()).length;$('#pendingCount').textContent=pending.length;$('#doneCount').textContent=done.length;$('#revenue').textContent=`S/ ${revenue.toFixed(2)}`;$('#reportRevenue').textContent=`S/ ${revenue.toFixed(2)}`;$('#reportDone').textContent=done.length;updateShopNameUI();renderUpcoming();renderAppointments();renderReport()}
function renderUpcoming(){const rows=data.appointments.filter(a=>a.status!=='done').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,6);$('#upcoming').innerHTML=rows.length?rows.map(a=>`<div class="appointment-row"><div><b>${esc(a.name)}</b><small>${esc(a.phone)} · ${a.date}</small></div><strong>${esc(a.time)}</strong><span class="status pending">No completada</span></div>`).join(''):'<p class="muted">No hay citas pendientes.</p>'}
function renderAppointments(){const q=($('#appointmentSearch').value||'').toLowerCase(),f=$('#appointmentFilter').value;const rows=data.appointments.filter(a=>(f==='all'||a.status===f)&&(`${a.name} ${a.phone}`).toLowerCase().includes(q)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('#appointmentTable').innerHTML=rows.length?rows.map(a=>`<tr><td><b>${esc(a.name)}</b></td><td>${esc(a.phone)}</td><td>${a.date}</td><td>${a.time}</td><td><b>S/ ${Number(a.amount||0).toFixed(2)}</b></td><td><span class="status ${a.status==='done'?'done':'pending'}">${a.status==='done'?'Completada':'No completada'}</span></td><td>${a.status!=='done'?`<button class="table-action" data-done="${a.id}">✓ Completar</button>`:`<button class="table-action" data-delete="${a.id}">Eliminar</button>`}</td></tr>`).join(''):'<tr><td colspan="7">No hay citas.</td></tr>'}
function renderReport(){const c=data.appointments.filter(a=>a.status==='done');$('#serviceReport').innerHTML=c.length?`<div class="bar-row"><span>Cortes completados</span><div class="bar"><i style="width:100%"></i></div><b>${c.length}</b></div><div class="bar-row"><span>Total cobrado</span><div class="bar"><i style="width:100%"></i></div><b>S/ ${c.reduce((n,a)=>n+Number(a.amount||0),0).toFixed(2)}</b></div>`:'<p class="muted">Completa citas para ver el resumen.</p>'}
function download(filename,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function rowsForExport(){return data.appointments.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))}
function exportWord(){const rows=rowsForExport(),name=esc(data.shopName||DEFAULT_NAME);const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial;padding:30px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #999;padding:8px;text-align:left}th{background:#eee}.total{margin-top:20px;font-weight:bold}</style></head><body><h1>${name}</h1><p>Reporte de citas</p><table><tr><th>Cliente</th><th>Número</th><th>Fecha</th><th>Hora</th><th>Monto</th><th>Estado</th></tr>${rows.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.phone)}</td><td>${a.date}</td><td>${a.time}</td><td>S/ ${Number(a.amount||0).toFixed(2)}</td><td>${a.status==='done'?'Completada':'No completada'}</td></tr>`).join('')}</table><p class="total">Ingresos completados: S/ ${rows.filter(a=>a.status==='done').reduce((n,a)=>n+Number(a.amount||0),0).toFixed(2)}</p></body></html>`;download(`${(data.shopName||DEFAULT_NAME).replace(/[^a-z0-9áéíóúñ ]/gi,'').trim().replace(/\s+/g,'-')||'barberia'}-${today()}.doc`,new Blob([html],{type:'application/msword'}))}
function exportPdf(){const rows=rowsForExport(),name=esc(data.shopName||DEFAULT_NAME),w=window.open('','_blank');if(!w){toast('Permite ventanas emergentes para exportar PDF');return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${name}</title><style>body{font-family:Arial;padding:25px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #999;padding:6px;text-align:left}th{background:#eee}.total{font-weight:bold;margin-top:20px}@media print{button{display:none}}</style></head><body><h1>${name}</h1><p>Reporte de citas</p><button onclick="print()">Imprimir / Guardar como PDF</button><table><tr><th>Cliente</th><th>Número</th><th>Fecha</th><th>Hora</th><th>Monto</th><th>Estado</th></tr>${rows.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.phone)}</td><td>${a.date}</td><td>${a.time}</td><td>S/ ${Number(a.amount||0).toFixed(2)}</td><td>${a.status==='done'?'Completada':'No completada'}</td></tr>`).join('')}</table><p class="total">Ingresos completados: S/ ${rows.filter(a=>a.status==='done').reduce((n,a)=>n+Number(a.amount||0),0).toFixed(2)}</p></body></html>`);w.document.close()}
$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.section)));$$('[data-section]').forEach(b=>{if(!b.classList.contains('nav'))b.addEventListener('click',()=>go(b.dataset.section))});$$('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));$$('[data-close]').forEach(b=>b.addEventListener('click',closeModal));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal()}));$('#appointmentDate').value=today();
$('#appointmentForm').addEventListener('submit',e=>{e.preventDefault();const date=$('#appointmentDate').value,time=$('#appointmentTime').value;if(data.appointments.some(a=>a.status!=='done'&&a.date===date&&a.time===time)){toast('Ya existe una cita pendiente a esa hora');return}data.appointments.push({id:Date.now(),name:$('#appointmentName').value.trim(),phone:$('#appointmentPhone').value.trim(),date,time,amount:Number($('#appointmentAmount').value),status:'pending'});save();render();closeModal();e.target.reset();$('#appointmentDate').value=today();toast('Cita guardada como no completada')});
$('#appointmentTable').addEventListener('click',e=>{if(e.target.dataset.done){const a=data.appointments.find(x=>x.id===Number(e.target.dataset.done));if(a){a.status='done';a.completedAt=new Date().toISOString();save();render();toast('Cita marcada como completada')}}if(e.target.dataset.delete){data.appointments=data.appointments.filter(x=>x.id!==Number(e.target.dataset.delete));save();render();toast('Cita eliminada')}});
$('#appointmentSearch').addEventListener('input',renderAppointments);$('#appointmentFilter').addEventListener('change',renderAppointments);
$('#saveSettings').addEventListener('click',()=>{const input=$('#shopName');const name=input.value.trim();if(!name){toast('Escribe un nombre para la barbería');input.focus();return}data.shopName=name;save();updateShopNameUI();toast('Nombre guardado correctamente')});
$('#shopName').addEventListener('keydown',e=>{if(e.key==='Enter')$('#saveSettings').click()});$('#exportWord').addEventListener('click',exportWord);$('#exportPdf').addEventListener('click',exportPdf);render();